### ISSUE TITLE
[Feature request] Allow option to treat some unfilled slots as "transparent"

### ISSUE THREAD

**Issue by LuminaSapphira** [AtaeKurri/Bartender#1]
Currently, when loading bars, slots that are unfilled cause those slots to be cleared when loading profiles. While I believe this is the ideal behavior, I think it would be cool to see an option to designate individual slots as "transparent" - meaning they do _not_ overwrite whatever is already present in the corresponding bar + slot in-game. 

This feature would allow for using this plugin to create a layered setup of profiles, where the first could assign some general buttons, and subsequent layers get more specific.

For example, consider the following 3 layers:

1. General
  a. Sprint @ 12, Mount @ 11, Limit break @ 10 -- [1, 9] transparent
2. Tank Role actions
  a. Rampart @ 9, Reprisal @ 8 -- [1,7], [10,12] transparent
3. Paladin
  a. Basic combo @ 1,2,3

Applying 3, then 2, then 1 sequentially yields a complete bar for player usage:
 - Basic combo @ 1,2,3
 - Reprisal @ 8, Rampart @ 9
 - Limit break @ 10, Mount @ 11, Sprint @ 12
 - ((4-7 empty))

This could be implemented in the UI by allowing users to click on individual slots to toggle their transparency. Code-wise it'd require skipping transparent slots when setting slots, which should be a fairly simple change.

**Comment by AtaeKurri** [comment]
Hi!
Thank you for the suggestion! o/

This is indeed a good idea, I'll see if/how I can implement this! ^^

**Comment by AtaeKurri** [comment]
Implemented in d1281feed5820758d00f5471fe3c281c3751d756
Thank you for the suggestion! o/
