### ISSUE TITLE
Feature Request: Add "Has Buff (X)" as automation condition

### ISSUE THREAD

**Issue by Cardinite30** [AtaeKurri/Bartender#3]
Example use case:

Would allow for Blue Mage to load the correct hotbars for group and solo content

[Has Buff] [Aetheric Mimicry: Healer]: Load Party Healer hotbar profile
[&&] [Has Buff] [Basic Instinct]: Load Solo Healer hotbar profile

**Comment by AtaeKurri** [comment]
Added with bcf4f9be403f8735a36f42532a3d8654263c2e55.
Thanks for the suggestion! o/
